export interface FacturaListado {
    registros: Factura[];
    totalRegistros: number;
}

export interface FacturaResponse {
    factura: DetalleFactura;
    partidas: Partida[];
    formaPago: FormaPago[];
}

export interface DetalleFactura {
    cve_cte: string;
    tel1_cte: string;
    fax_cte: string;
    cve_factu: string;
    lugar: string;
    status_fac: string;
    stat_canc: string;
    status_2: string;
    no_fac: string;
    falta_fac: string;
    hora_fac: string;
    observa: string;
    rfc_cte: string;
    nom_cte: string;
    dir_cte: string;
    ni_cte: string;
    ne_cte: string;
    cd_cte: string;
    col_cte: string;
    delega_cte: string;
    edo_cte: string;
    pais_cte: string;
    cp_cte: string;
    cve_mon: string;
    moneda: string;
    tip_cam: string;
    email_cte: string;
    nom_ent: string;
    dir_ent: string;
    ni_ent: string;
    ne_ent: string;
    col_ent: string;
    cd_ent: string;
    delega_ent: string;
    edo_ent: string;
    pais_ent: string;
    cp_ent: string;
    resi_ent: string;
    cve_col: string;
    cve_mpio: string;
    cve_local: string;
    cve_edo: string;
    chk_dir: string;
    tpo_manent: string;
    des_etiq1: string;
    dato_1: string;
    des_etiq2: string;
    dato_2: string;
    des_etiq3: string;
    dato_3: string;
    des_etiq4: string;
    dato_4: string;
    des_etiq5: string;
    dato_5: string;
    des_etiq6: string;
    dato_6: string;
    des_etiq7: string;
    dato_7: string;
    des_etiq8: string;
    dato_8: string;
    des_etiq9: string;
    dato_9: string;
    des_etiq10: string;
    dato_10: string;
    des_etiq11: string;
    dato_11: string;
    des_etiq12: string;
    dato_12: string;
    no_peda: string;
    cve_suca: string;
    cve_factua: string;
    descue: string;
    descue2: string;
    descue3: string;
    descue4: string;
    nmretot: string;
    importeg: string;
    descuentog: string;
    subtotalg: string;
    iepsg: string;
    ivag: string;
    retisrg: string;
    retivag: string;
    impto1g: string;
    impto2g: string;
    titde1: string;
    titde2: string;
    titde3: string;
    titde4: string;
    titde5: string;
    titde6: string;
    titde7: string;
    titde8: string;
    nomde1: string;
    nomde2: string;
    nomde3: string;
    nomde4: string;
    nomde5: string;
    nomde6: string;
    nomde7: string;
    nomde8: string;
    cvede1: string;
    cvede2: string;
    cvede3: string;
    cvede4: string;
    cvede5: string;
    cvede6: string;
    cvede7: string;
    cvede8: string;
    totalg: string;
    cve_age: string;
    cve_age2: string;
    numpol: string;
    cve_factut: string;
    no_remt: string;
    nombre_dev: string;
    nom_age1: string;
    nom_age2: string;
    tooltip: string;
    codestatus: string;
    nombre_archivo: string;
    nombre_acu: string;
    total_letra: string;
    tooltip_fecha: string;
    leyimp1: string;
    leyimp2: string;
    ped_int: string;
    editod: string;
    editde: string;
    ladam_cte: string;
    movil_cte: string;
}

export interface Partida {
    imagpath: string;
    cant_prod: string; // Si prefieres número: number;
    unidad: string;
    cve_prod: string;
    new_med: string;
    desc_prod: string;
    desclarga: string;
    deta_prod: string;
    valor_prod: string; // Si prefieres número: number;
    subtotalpartidas: string; // Si prefieres número: number;
    dcto1: string;
    dcto2: string;
    desc_cteg: string;
    importe: string;
    descuento: string;
    subtotal: string;
    ieps: string;
    iva: string;
    retisr: string;
    retiva: string;
    total: string;
    cve_carac: string;
    nom_carac: string;
    eskit: string;
    kpc: string;
    carac_prod: string;
    lote: string;
    ref_lote: string;
    partida: string;
    cve_cataf: string;
    imp_calg: string;
    sub_calg: string;
    tot_calg: string;
}

export interface FormaPago {
    cveFactu: string;
    noFac: string;
    tipo: string;
    subtipo: string;
    cantsub: number | string;
    trans: number | string;
    deposito: number | string;
    sucDepo: string;
    numetarje: string;
    cantsubc: number | string;
}

export interface Factura {
    sucursal: string;
    nom_age: string;
    nom_cte: string;
    faltaped: string;
    cve_age: string;
    status_fac: string;
    total_fac: string;
    cve_mon: string;
    no_fac: string;
    cve_suc: string;
    cve_factu: string;
    falta_fac: Date;
    cve_cte: string;
    lugar: string;
    nombre_archivo: string;
    codestatus: string;
    nombre_dev: string;
    nombre_acu: string;
}
